import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { ReactQueryProvider } from "@/utils/react-query-provider";
import TopNavLayout from "./(navlayout)/navlayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recipes.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
        <div className="w-full bg-gray-50 min-h-screen">
          <div className="max-w-[70rem] mx-auto bg-white min-h-screen px-10"><TopNavLayout>{children}</TopNavLayout> </div>
        </div>
        </ReactQueryProvider>
        <ToastContainer autoClose={2000} theme="colored" />
      </body>
    </html>
  );
}
